/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHelloRouteImport } from './routes/api/hello'
import { Route as ApiHelloNameRouteImport } from './routes/api/hello/$name'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloNameRoute = ApiHelloNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ApiHelloRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/hello': typeof ApiHelloRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/hello/$name': typeof ApiHelloNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/hello': typeof ApiHelloRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/hello/$name': typeof ApiHelloNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/hello': typeof ApiHelloRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/hello/$name': typeof ApiHelloNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/hello' | '/api/search' | '/api/hello/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/api/hello' | '/api/search' | '/api/hello/$name'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/hello'
    | '/api/search'
    | '/api/hello/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiHelloRoute: typeof ApiHelloRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hello/$name': {
      id: '/api/hello/$name'
      path: '/$name'
      fullPath: '/api/hello/$name'
      preLoaderRoute: typeof ApiHelloNameRouteImport
      parentRoute: typeof ApiHelloRoute
    }
  }
}

interface ApiHelloRouteChildren {
  ApiHelloNameRoute: typeof ApiHelloNameRoute
}

const ApiHelloRouteChildren: ApiHelloRouteChildren = {
  ApiHelloNameRoute: ApiHelloNameRoute,
}

const ApiHelloRouteWithChildren = ApiHelloRoute._addFileChildren(
  ApiHelloRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiHelloRoute: ApiHelloRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
